{% set version = '1.4.5.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgooglemaps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RgoogleMaps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RgoogleMaps/RgoogleMaps_{{ version }}.tar.gz
  sha256: d1d5ad8db841754af175d4104a05c5c31e5cc445be314a3ac70483c31798680b

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-png
    - r-sp
  run:
    - r-base
    - r-png
    - r-sp

test:
  commands:
    - $R -e "library('RgoogleMaps')"           # [not win]
    - "\"%R%\" -e \"library('RgoogleMaps')\""  # [win]

about:
  home: https://github.com/markusloecher/rgooglemaps/blob/master/rgooglemaps/www/QuickTutorial.html
  license: GPL-2.0-or-later
  summary: 'Serves two purposes: (i) Provide a comfortable R interface to query the Google server
    for static maps, and (ii) Use the map as a background image to overlay plots within
    R. This requires proper coordinate scaling.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - druvus

# Package: RgoogleMaps
# Type: Package
# Title: Overlays on Static Maps
# Version: 1.4.5.3
# Date: 2020-02-12
# Depends: R (>= 2.10)
# Imports: graphics, stats, utils, grDevices, methods, png,sp
# Suggests: PBSmapping, maptools, loa, RColorBrewer, leaflet,jpeg, RCurl
# Author: Markus Loecher
# URL: https://github.com/markusloecher/rgooglemaps/blob/master/rgooglemaps/www/QuickTutorial.html
# Maintainer: Markus Loecher <markus.loecher@gmail.com>
# Description: Serves two purposes: (i) Provide a comfortable R interface to query the Google server for static maps, and (ii) Use the map as a background image to overlay plots within R. This requires proper coordinate scaling.
# License: GPL
# LazyLoad: yes
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2020-02-12 13:11:09 UTC; loecherm
# Date/Publication: 2020-02-12 14:30:09 UTC
