travis:
  secure:
    BINSTAR_TOKEN: GkpgExnKSUuDs2hjhRIYw57FSS4nGacM40cZRyDZWM/irziWi9uGGiUhLrXTlY2+e+LQmXLQQJmIs2oKS1MwQtdMwagOQSL7g4xStCZ9JdeKNmur5ifOI116T08Fh9TrfVjBjQUctbCpEpkti+0a69kEcQ43UEK5p0fIWZ3dbB0LtvfIPE7PI/zcwBkDffLcjqxVqFIORXW7FSzZLghRIFPjfZM3uFsPTvPPeVqrBBXYj/eU6NoevsJ79vxGn6n6gvm+boASh7C8SkcxcjbclgNW9wM5IusO06YEGgPodQKtR74P8ZLV+nOSea/I227IthJVyE6ztylbTCpoVKHWiVrGBX3QkFSHIA4HOEqBOwDLaQ47wOftYHkHThHgnbDv/r4Uiw1YJAqwSEQbdaMKfynD91BoPEkaF06jT8pFvte13cVbX+AR6oOfgTVfYujJkTfZ15u7OQbG2He3sHOD2fwoVN95RtHnu4XVJ9ukjQKvh6mljBkRQ2oGGzHrs0pN1RxCLAry4LrnnLFr5jBA2UR9DaleGC6shZhr6PBsb5GxWIUWXajKAHqizYMyO7iK6/vHuFIS4RlVfmz/dMxrWnJMxfss6aEE/wzSyTTe8xsiFKq/LpwMUn7o3x6Uh8DCjbvzwJlWmO5pP5mViFbnK/jx4B+Rzy53xIlOJ6f78NM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
