appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: SrnlnN9j5WRE3JwTX6Jmm+uEy2xA8AcqNKSSWgGHglN2srV3slAMJeVFuBVz5osbBRCoi6xhD+YkRmzoMXXORlns+jf+axN/84oT8kX4XrVo41OJ/tgG+lToIClb7uyvX8/YRl17Z0o3rTA5kQxzaWS20mjiU8JKlzpOnhZD7+Bgx6StF3tiJhQm+Nuwl5Rtl42Rl9qdAf/IjdpjlqLivG26Qqndbf/pAB9qNmr2d4ZzkbQZuQr67cjSVbQdY5ct/2aMpfvvikOZbDSwv7RE8WsqdHOjI2C/HadcvsgEEQRvjtiRQIDVnDFD328Mv6Clg0JgKB/FVzf3uUFX4TIKe6gT8lIKQqhp8nNwVwIIPxrmuk3FrwyDDNHd71WldhkNXGzoDzopfpiVgLTu/wynZ736EGx71aI9uh/2LnQmITdf6PRHM+KICa8n+LSV8Wei20DhskjgYMtqV0k2su/9BQxwGfYWJ9Di3qC6Axzi6umHj95v7cRVkM4er4CpuEzadGbSWHUFQ6JhGPt78Dvpnfq5dQkmUOM3Qij027ppdLwb3kPeHEbFt0doa7TyFXqOgVfPNP04lDr4/xozCGlGBoQcXtRAak0N+4bKwCUwMWXaqFDQLPGAPHij5TzSbZqzpqUI61W1ANaX++Oy9lME1l4mrFz4FKFn1aZ3+g/AkfY=
